version: 1.0.{build}
image: Visual Studio 2019
skip_tags: true
branches:
  only:
  - master
configuration: Release
before_build:
- ps: >-
    nuget restore

    . "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64\sn.exe" -k ./PostScriptValidator/PostScriptValidator.snk
build:
  project: PostScriptValidator.sln
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

artifacts:
- path: '**\PostScriptValidator.*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: BAGacXk+5m7jd8EvWW6wkYhoVml39WAi7n2Z0odVUKUq5SeWLqixvkPA1I+KbQ1r
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: nr/Bs1CExU8FMlqvNgtkCcHPBqi+JaIgL0d0vNkQx5AzklU+u/Dt6NqhWlh94duJ