version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- ps: nuget restore
build:
  project: PostScriptValidator.sln
  verbosity: minimal
artifacts:
- path: '**\PostScriptValidator.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: uam/dXnhJv544YdAQNP+mKC9fkL7UFQydK/55TWjozWEswDWNUBh/Mq/WLv8Fa8U
- provider: GitHub
  auth_token:
    secure: nr/Bs1CExU8FMlqvNgtkCcHPBqi+JaIgL0d0vNkQx5AzklU+u/Dt6NqhWlh94duJ